sonar.projectKey=opsledger-app
sonar.projectName=opsledger-app
sonar.projectVersion=1.0

sonar.sources=src/
sonar.java.binaries=target/classes

sonar.junit.reportsPath=target/surefire-reports/
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.checkstyle.reportPaths=target/checkstyle-result.xml